version: "3.9"  # optional since v1.27.0
services: 
  web:
    build: .
    container_name: sisaqweb-app
    hostname: sisaqweb-app
    restart: always
    networks:
      net_two:
        ipv4_address: 10.2.0.6 
    volumes: 
      - /c/development/pessoal/pucminas_tutoria/poc/sisaqweb/dist/sisaqweb:/usr/local/apache2/htdocs/sisaqweb/:rw
#    ports:  
#      - 80:80
  
networks: 
  net_two:
    external: true
    name: net_two