#!/bin/bash

set -e

export PGPASSWORD=postgres

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER sisaq WITH PASSWORD 'sisaq';
CREATE DATABASE sisaq;
GRANT ALL PRIVILEGES ON DATABASE sisaq TO sisaq;
EOSQL

export PGPASSWORD=sisaq

psql -v ON_ERROR_STOP=1 --username "sisaq" --dbname "sisaq" <<-EOSQL

CREATE SEQUENCE SOLICITACAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SOLICITACAO (
	ID INT NOT NULL,
	DESCRICAO VARCHAR(2000) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	QTD INT NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	ATIVO_ID INT NOT NULL,
	
	CONSTRAINT PK_SOLICITACAO PRIMARY KEY(ID)
);

CREATE INDEX IDX_SOLICITACAO_ATIVO_ID ON SOLICITACAO(ATIVO_ID);

CREATE SEQUENCE AQUISICAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE AQUISICAO (
	ID INT NOT NULL,
	QTD INT NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	NOTA_FISCAL VARCHAR(10) NOT NULL,
	VALOR NUMERIC(12,2) NOT NULL, 
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	SOLICITACAO_ID INT NOT NULL,
	
	CONSTRAINT PK_AQUISICAO PRIMARY KEY(ID),
	CONSTRAINT FK_AQUISICAO_SOLICITACAO FOREIGN KEY(SOLICITACAO_ID) REFERENCES SOLICITACAO(ID)
);

CREATE UNIQUE INDEX AQUISICAO_CPNJ_NOTA_FISCAL_IDX ON AQUISICAO(CNPJ,NOTA_FISCAL);

ALTER TABLE AQUISICAO ADD CONSTRAINT UQ_AQUISICAO_CPNJ_NOTA_FISCAL UNIQUE USING INDEX AQUISICAO_CPNJ_NOTA_FISCAL_IDX;

EOSQL
