#!/bin/bash

set -e

export PGPASSWORD=postgres

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER sisaq WITH PASSWORD 'sisaq';
CREATE DATABASE sisaq;
GRANT ALL PRIVILEGES ON DATABASE sisaq TO sisaq;
EOSQL

export PGPASSWORD=sisaq

psql -v ON_ERROR_STOP=1 --username "sisaq" --dbname "sisaq" <<-EOSQL

CREATE SEQUENCE INSUMO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE INSUMO (
	ID INT NOT NULL,
	DESCRICAO VARCHAR(2000) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,

	CONSTRAINT PK_INSUMO PRIMARY KEY(ID)
);

CREATE SEQUENCE SOLICITACAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SOLICITACAO (
	ID INT NOT NULL,
	QTD INT NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	INSUMO_ID INT NOT NULL,
	
	CONSTRAINT PK_SOLICITACAO PRIMARY KEY(ID),
	CONSTRAINT FK_SOLICITACAO_INSUMO FOREIGN KEY(INSUMO_ID) REFERENCES INSUMO(ID)
);

CREATE SEQUENCE AQUISICAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE AQUISICAO (
	ID INT NOT NULL,
	QTD INT NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	SOLICITACAO_ID INT NOT NULL,
	
	CONSTRAINT PK_AQUISICAO PRIMARY KEY(ID),
	CONSTRAINT FK_AQUISICAO_SOLICITACAO FOREIGN KEY(SOLICITACAO_ID) REFERENCES SOLICITACAO(ID)
);

CREATE SEQUENCE ALOCACAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ALOCACAO (
	ID INT NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	AQUISICAO_ID INT NOT NULL,
	
	CONSTRAINT PK_ALOCACAO PRIMARY KEY(ID),
	CONSTRAINT FK_ALOCACAO_AQUISICAO FOREIGN KEY(AQUISICAO_ID) REFERENCES AQUISICAO(ID)
);
EOSQL
