#!/bin/bash

set -e

export PGPASSWORD=postgres

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER sisca WITH PASSWORD 'sisca';
CREATE DATABASE sisca;
GRANT ALL PRIVILEGES ON DATABASE sisca TO sisca;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "sisca" <<-EOSQL
CREATE EXTENSION postgis;
EOSQL

export PGPASSWORD=sisca

psql -v ON_ERROR_STOP=1 --username "sisca" --dbname "sisca" <<-EOSQL

CREATE SEQUENCE ATIVO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ATIVO (
	ID NUMERIC NOT NULL,
	DESCRICAO VARCHAR(2000) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	DURAVEL BOOLEAN,

	CONSTRAINT PK_ATIVO PRIMARY KEY(ID)
);

CREATE SEQUENCE PATRIMONIO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PATRIMONIO (
	ID NUMERIC NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	ATIVO_ID NUMERIC NOT NULL,

	CONSTRAINT PK_PATRIMONIO PRIMARY KEY(ID),
	CONSTRAINT FK_PATRIMONIO_ATIVO FOREIGN KEY(ATIVO_ID) REFERENCES ATIVO(ID)
);

CREATE SEQUENCE LOCAL_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE LOCAL (
	ID NUMERIC NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	POINT GEOMETRY NOT NULL,

	CONSTRAINT PK_LOCAL PRIMARY KEY(ID)
);

CREATE INDEX IDX_LOCAL_POINT ON LOCAL USING GIST(POINT);

CREATE SEQUENCE ALOCACAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ALOCACAO (
	ID NUMERIC NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	ATIVO_ID NUMERIC NOT NULL,
	PATRIMONIO_ID NUMERIC NOT NULL,
	LOCAL_ID NUMERIC NOT NULL,
	AQUISICAO_ID NUMERIC NOT NULL,

	CONSTRAINT PK_ALOCACAO PRIMARY KEY(ID),
	CONSTRAINT FK_ALOCACAO_ATIVO FOREIGN KEY(ATIVO_ID) REFERENCES ATIVO(ID),
	CONSTRAINT FK_ALOCACAO_PATRIMONIO FOREIGN KEY(PATRIMONIO_ID) REFERENCES PATRIMONIO(ID),
	CONSTRAINT FK_ALOCACAO_LOCAL FOREIGN KEY(LOCAL_ID) REFERENCES LOCAL(ID)
);

CREATE INDEX IDX_ALOCACAO_AQUISICAO_ID ON ALOCACAO(AQUISICAO_ID);

EOSQL
