#!/bin/bash

set -e

export PGPASSWORD=postgres

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER sismb WITH PASSWORD 'sismb';
CREATE DATABASE sismb;
GRANT ALL PRIVILEGES ON DATABASE sismb TO sismb;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "sismb" <<-EOSQL
CREATE EXTENSION postgis;
EOSQL

export PGPASSWORD=sismb

psql -v ON_ERROR_STOP=1 --username "sismb" --dbname "sismb" <<-EOSQL

CREATE SEQUENCE BARRAGEM_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE BARRAGEM (
	ID NUMERIC NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	POLYGON GEOMETRY NOT NULL,

	CONSTRAINT PK_BARRAGEM PRIMARY KEY(ID)
);

CREATE INDEX IDX_BARRAGEM_POLYGON ON BARRAGEM USING GIST(POLYGON);

CREATE SEQUENCE SENSOR_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SENSOR (
	ID NUMERIC NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	BARRAGEM_ID NUMERIC NOT NULL,

	CONSTRAINT PK_SENSOR PRIMARY KEY(ID),
	CONSTRAINT FK_SENSOR_BARRAGEM FOREIGN KEY(BARRAGEM_ID) REFERENCES BARRAGEM(ID)
);

CREATE SEQUENCE VAZAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE VAZAO (
	ID NUMERIC NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	DATA TIMESTAMP NOT NULL,
	POINT GEOMETRY NOT NULL,
	SENSOR_ID NUMERIC NOT NULL,

	CONSTRAINT PK_VAZAO PRIMARY KEY(ID),
	CONSTRAINT FK_VAZAO_SENSOR FOREIGN KEY(SENSOR_ID) REFERENCES SENSOR(ID)
);

CREATE INDEX IDX_VAZAO_POINT ON VAZAO USING GIST(POINT);

CREATE SEQUENCE CARGA_TENSAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE CARGA_TENSAO (
	ID NUMERIC NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	DATA TIMESTAMP NOT NULL,
	POINT GEOMETRY NOT NULL,
	SENSOR_ID NUMERIC NOT NULL,

	CONSTRAINT PK_CARGA_TENSAO PRIMARY KEY(ID),
	CONSTRAINT FK_CARGA_TENSAO_SENSOR FOREIGN KEY(SENSOR_ID) REFERENCES SENSOR(ID)
);

CREATE INDEX IDX_CARGA_TENSAO_POINT ON CARGA_TENSAO USING GIST(POINT);

CREATE SEQUENCE INCLINOMETRO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE INCLINOMETRO (
	ID NUMERIC NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	DATA TIMESTAMP NOT NULL,
	POINT GEOMETRY NOT NULL,
	SENSOR_ID NUMERIC NOT NULL,

	CONSTRAINT PK_INCLINOMETRO PRIMARY KEY(ID),
	CONSTRAINT FK_INCLINOMETRO_SENSOR FOREIGN KEY(SENSOR_ID) REFERENCES SENSOR(ID)
);

CREATE INDEX IDX_INCLINOMETRO_POINT ON INCLINOMETRO USING GIST(POINT);

CREATE SEQUENCE PIEZOMETRO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PIEZOMETRO (
	ID NUMERIC NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	TEMPERATURA NUMERIC(10,2) NOT NULL,
	DATA TIMESTAMP NOT NULL,
	POINT GEOMETRY NOT NULL,
	SENSOR_ID NUMERIC NOT NULL,

	CONSTRAINT PK_PIEZOMETRO PRIMARY KEY(ID),
	CONSTRAINT FK_PIEZOMETRO_SENSOR FOREIGN KEY(SENSOR_ID) REFERENCES SENSOR(ID)
);

CREATE INDEX IDX_PIEZOMETRO_POINT ON PIEZOMETRO USING GIST(POINT);

EOSQL
