version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    container_name: sisca
    hostname: sisca
    restart: always
    networks:
      net_one:
        ipv4_address: 10.1.0.5
#   ports:
#     - 8080:8080
networks: 
  net_one: 
    external: true
    name: net_one         